image: Ubuntu

environment:
  LANG: en_US.UTF-8

build_script:
  - pwsh: $env:LANG; Install-Module -Name Pester -Force -Scope CurrentUser; Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser; Invoke-Pester ./Tests/Documentation/RuleDocumentation.tests.ps1