steps:
- task: DownloadPipelineArtifact@2
  displayName: 'Download Pipeline Artifact: out Folder'
  inputs:
    artifactName: out
    targetPath: '$(Build.SourcesDirectory)/out'
- task: DownloadPipelineArtifact@2
  displayName: 'Download Pipeline Artifact: Tests Folder'
  inputs:
    artifactName: Tests
    targetPath: '$(Build.SourcesDirectory)/tests'
- task: DownloadPipelineArtifact@2
  displayName: 'Download Pipeline Artifact: tools Folder'
  inputs:
    artifactName: tools
    targetPath: '$(Build.SourcesDirectory)/tools'
- task: PowerShell@2
  displayName: 'Test'
  inputs:
    targetType: inline
    pwsh: false
    script: |
      Import-Module .\tools\appveyor.psm1
      Invoke-AppveyorTest -CheckoutPath $env:BUILD_SOURCESDIRECTORY
- task: PublishTestResults@2
  inputs:
    testRunner: NUnit
    testResultsFiles: 'testResults.xml'
  condition: succeededOrFailed()
