variables:
  # Avoid expensive initialization of dotnet cli, see: https://donovanbrown.com/post/Stop-wasting-time-during-NET-Core-builds
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  VmImages: [ 'ubuntu-16.04', 'windows-latest' ]
  PowerShellVersions: [ 'LTS', 'Preview' ]

stages:
  - stage: Build
    jobs:
      - job: 'Full_Build'
        pool:
          vmImage: windows-latest
        steps:
        - pwsh: |
            Import-Module .\tools\appveyor.psm1
            Invoke-AppveyorInstall -SkipPesterInstallation
            ./build.ps1 -Configuration 'Release' -All
            ./PSCompatibilityCollector/build.ps1 -Configuration 'Release'
          displayName: 'Full Build'
        - task: PublishPipelineArtifact@1
          displayName: 'Publish Pipeline Artifact: out Folder'
          inputs:
            targetPath: '$(Build.SourcesDirectory)/out'
            artifactName: out
  - stage: Test
    jobs:
      - ${{ each image in variables.PowerShellVersions }}:
        - ${{ each image in variables.vmImages }}:
          job:
          pool:
            vmImage: ${{ variables.VmImages }}
          steps:
          - template: templates/test.yaml
