variables:
  # Avoid expensive initialization of dotnet cli, see: https://donovanbrown.com/post/Stop-wasting-time-during-NET-Core-builds
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

stages:
  - stage: Build
    jobs:
      - job: 'Full_Build'
        pool:
          vmImage: windows-latest
        steps:
        - pwsh: |
            mkdir out
            # Import-Module .\tools\appveyor.psm1
            # Invoke-AppveyorInstall -SkipPesterInstallation
            # ./build.ps1 -Configuration 'Release' -All
            # ./PSCompatibilityCollector/build.ps1 -Configuration 'Release'
          displayName: 'Full Build'
        - task: PublishPipelineArtifact@1
          displayName: 'Publish Pipeline Artifact: out Folder'
          inputs:
            targetPath: '$(Build.SourcesDirectory)/out'
            artifactName: out
  - stage: Test
    jobs:
    - template: templates/test.yaml
      parameters:
        images: [ 'ubuntu-16.04', 'vs2017-win2016' ]
        powerShellVersions: [ 'LTS', 'Preview' ]
